name: Minimal

env:
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  CARGO_UNSTABLE_SPARSE_REGISTRY: true

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'

jobs:
  minimal:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Install nightly rust
      run: rustup toolchain install nightly --no-self-update --profile minimal

    - name: Create Cargo.lock containing the minimal versions
      run: cargo +nightly update -Zminimal-versions

    - uses: Swatinem/rust-cache@v2
    - name: Check with minimal version of deps
      run: cargo check --lib --locked
