name: Miri

env:
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  CARGO_UNSTABLE_SPARSE_REGISTRY: true

on:
  push:
    branches: [none]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
  #pull_request:
  #  paths-ignore:
  #    - 'README.md'
  #    - 'LICENSE'
  #    - '.gitignore'

jobs:
  miri:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Install latest nightly
      run: |
        rustup toolchain install nightly --component miri --no-self-update --profile minimal
        rustup default nightly
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-nextest

    - uses: Swatinem/rust-cache@v2
    - name: Miri
      run: |
        cargo +nightly miri \
            nextest run \
            -Z build-std \
            --target "$(rustc -vV | grep host | cut -d : -f 2 | tr -d '[:space:]')" \
            --release
      env:
        MIRIFLAGS: -Zmiri-disable-isolation
